name: "ğŸ“Š Analyze the Repository"

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: '31 21 * * 1'

jobs:
  inclusion:
    name: "ğŸŒ Inclusion Analysis"
    uses: microsoft/InclusivenessAnalyzer@v1.0.1
    with:
      failOnNonInclusiveTerm: true

  codeQl:
    name: "ğŸ”’ Security Analysis"
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        language: [ 'csharp' ]
    steps:
    - name: "âœ… Checkout Repository"
      uses: actions/checkout@v3

    - name: "ğŸ”‘ Initialize CodeQL"
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}

    - name: "ğŸ“¦ Autobuild"
      uses: github/codeql-action/autobuild@v2

    - name: "ğŸ‘ï¸ Analize"
      uses: github/codeql-action/analyze@v2
      with:
        category: "/language:${{matrix.language}}"