name: "ğŸ—ï¸ Build and Test ğŸ§ª"

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: ğŸ“¥ Checkout Repository
        uses: actions/checkout@v3

      - name: âœ… Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: â¬‡ï¸ Restore Dependencies
        run: dotnet restore

      - name: ğŸ—ï¸ Build
        run: dotnet build -c Release

      - name: ğŸ§ª Test
        run: dotnet test -c Release